/**
 * @file machineCatalog.ts
 * @description Real-world industrial machine specifications (Lathe, Milling, CNC, Laser, Press Brake, 3D Printer).
 * Sourced from standard manufacturing equipment specs (Haas, Mazak, DMG Mori, Amada, Trumpf, HMT, Bridgeport).
 */

import { IMachine } from "@/types";

export const STANDARD_INDUSTRIAL_MACHINES: IMachine[] = [
  {
    id: "mac-lathe-01",
    name: "Mazak Quick Turn 250MSY CNC Turning Center (Lathe)",
    machineType: "CNC Turning (Lathe)",
    xAxisMm: 230,
    yAxisMm: 100,
    zAxisMm: 575,
    maxPartSizeMm: 380,
    hourlyRateInr: 1100,
    isActive: true,
    supportedMaterials: [
      "Mild Steel EN8",
      "Aluminum 6061-T6",
      "Stainless Steel 304",
      "Brass C360",
      "Delrin POM",
    ],
  },
  {
    id: "mac-lathe-02",
    name: "HMT NH22 Heavy Duty Precision Center Lathe (Manual)",
    machineType: "Manual Engine Lathe",
    xAxisMm: 220,
    yAxisMm: 0,
    zAxisMm: 1000,
    maxPartSizeMm: 440,
    hourlyRateInr: 650,
    isActive: true,
    supportedMaterials: ["Mild Steel", "Cast Iron", "Bronze", "Aluminum"],
  },
  {
    id: "mac-mill-01",
    name: "Haas VF-2SS Super-Speed CNC Vertical Machining Center",
    machineType: "CNC Milling (3-Axis VMC)",
    xAxisMm: 762,
    yAxisMm: 406,
    zAxisMm: 508,
    maxPartSizeMm: 750,
    hourlyRateInr: 1400,
    isActive: true,
    supportedMaterials: [
      "Aluminum 6061-T6",
      "Aluminum 7075-T6",
      "Stainless Steel 316L",
      "Tool Steel D2",
      "Brass",
    ],
  },
  {
    id: "mac-mill-02",
    name: "DMG Mori DMU 50 5-Axis Simultaneous Machining Center",
    machineType: "5-Axis CNC Milling",
    xAxisMm: 650,
    yAxisMm: 520,
    zAxisMm: 475,
    maxPartSizeMm: 630,
    hourlyRateInr: 2800,
    isActive: true,
    supportedMaterials: [
      "Titanium Grade 5",
      "Inconel 718",
      "Aerospace Aluminum 7050",
      "SS 316L",
    ],
  },
  {
    id: "mac-mill-03",
    name: "Bridgeport Series I Knee & Column Vertical Turret Milling",
    machineType: "Manual Turret Milling",
    xAxisMm: 760,
    yAxisMm: 305,
    zAxisMm: 406,
    maxPartSizeMm: 500,
    hourlyRateInr: 550,
    isActive: true,
    supportedMaterials: ["Mild Steel", "Aluminum", "Brass", "Cast Iron"],
  },
  {
    id: "mac-laser-01",
    name: "Amada Ensis 3015 AJ 4kW Fiber Laser Cutting System",
    machineType: "Fiber Laser Cutting",
    xAxisMm: 3070,
    yAxisMm: 1550,
    zAxisMm: 100,
    maxPartSizeMm: 3000,
    hourlyRateInr: 1800,
    isActive: true,
    supportedMaterials: [
      "Mild Steel CRCA (up to 20mm)",
      "Stainless Steel 304/316 (up to 12mm)",
      "Aluminum 5052 (up to 10mm)",
      "Copper/Brass",
    ],
  },
  {
    id: "mac-press-01",
    name: "Trumpf TruBend 5130 Precision CNC Press Brake (130 Ton)",
    machineType: "CNC Sheet Metal Bending",
    xAxisMm: 3230,
    yAxisMm: 440,
    zAxisMm: 615,
    maxPartSizeMm: 3200,
    hourlyRateInr: 1200,
    isActive: true,
    supportedMaterials: [
      "Sheet Metal Mild Steel",
      "Aluminum 5052-H32",
      "Galvanized Iron (GI)",
      "Stainless Steel 304",
    ],
  },
  {
    id: "mac-3d-01",
    name: "EOS M 290 Direct Metal Laser Sintering (DMLS) 3D Printer",
    machineType: "Metal 3D Printing (Additive)",
    xAxisMm: 250,
    yAxisMm: 250,
    zAxisMm: 325,
    maxPartSizeMm: 250,
    hourlyRateInr: 3200,
    isActive: true,
    supportedMaterials: [
      "Titanium Ti6Al4V",
      "Aluminum AlSi10Mg",
      "Stainless Steel 316L",
      "Cobalt Chrome",
    ],
  },
];
