/**
 * @file mockData.ts
 * @description High-fidelity mock seed data matching the Fabricaze Pitch Deck & User Mockups.
 * Powers client-side demonstration, fallback resilience, and immediate interactive fidelity.
 */

import { IManufacturer, IEnquiry, IQuotation, IOrder, IDispute } from '../types';

export const INITIAL_MANUFACTURERS: IManufacturer[] = [
  {
    id: 'mfg-001',
    companyName: 'Metro Manufacturing Co.',
    pseudoName: 'Metro Fabricators #PUN-9821',
    city: 'Pune',
    state: 'Maharashtra',
    rating: 4.6,
    reviewCount: 98,
    verificationStatus: 'VERIFIED',
    distanceKm: 12.8,
    responseTime: '< 4 hours',
    priceRange: '₹₹',
    capabilities: ['CNC Machining', 'Laser Cutting', 'Sheet Metal', 'Welding', 'Assembly'],
    certifications: ['ISO 9001', 'ISO 14001'],
    specialties: ['Industrial', 'Electronics'],
    machines: [
      {
        id: 'mac-1',
        name: 'Amada Fiber Laser 4kW',
        machineType: 'Laser Cutting',
        xAxisMm: 3000,
        yAxisMm: 1500,
        hourlyRateInr: 1800,
        isActive: true,
        supportedMaterials: ['SS 304', 'Aluminum 5052', 'Mild Steel'],
      },
      {
        id: 'mac-2',
        name: 'Trumpf TruBend 5130 Press Brake',
        machineType: 'Sheet Metal',
        hourlyRateInr: 1200,
        isActive: true,
        supportedMaterials: ['Aluminum', 'Mild Steel'],
      },
    ],
  },
  {
    id: 'mfg-002',
    companyName: 'Precision Tech Industries',
    pseudoName: 'Precision Tech #IND-4102',
    city: 'Indore',
    state: 'Madhya Pradesh',
    rating: 4.8,
    reviewCount: 142,
    verificationStatus: 'VERIFIED',
    distanceKm: 5.2,
    responseTime: '< 2 hours',
    priceRange: '₹₹₹',
    capabilities: ['CNC Machining', 'Laser Cutting', '3D Printing', 'Anodizing', 'Quality Inspection'],
    certifications: ['ISO 9001', 'AS9100'],
    specialties: ['Aerospace', 'Automotive'],
    machines: [
      {
        id: 'mac-3',
        name: 'Haas VF-2SS 3-Axis VMC',
        machineType: 'CNC Machining',
        xAxisMm: 762,
        yAxisMm: 406,
        zAxisMm: 508,
        hourlyRateInr: 1400,
        isActive: true,
        supportedMaterials: ['Aluminum 6061-T6', 'SS 304', 'Brass'],
      },
    ],
  },
  {
    id: 'mfg-003',
    companyName: 'Gujarat Engineering Works',
    pseudoName: 'Gujarat Precision #AHM-6512',
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.5,
    reviewCount: 76,
    verificationStatus: 'VERIFIED',
    distanceKm: 8.4,
    responseTime: '< 6 hours',
    priceRange: '₹₹₹₹',
    capabilities: ['CNC Machining', 'Casting', 'Heat Treatment', 'Surface Coating'],
    certifications: ['ISO 9001'],
    specialties: ['Heavy Machinery', 'Oil & Gas'],
    machines: [
      {
        id: 'mac-4',
        name: 'DMG Mori 5-Axis Milling Machine',
        machineType: '5-Axis CNC',
        hourlyRateInr: 2600,
        isActive: true,
        supportedMaterials: ['Inconel', 'Titanium', 'SS 316L'],
      },
    ],
  },
  {
    id: 'mfg-004',
    companyName: 'Advanced Machining Solutions',
    pseudoName: 'Advanced Fab Solutions #PUN-7719',
    city: 'Pune',
    state: 'Maharashtra',
    rating: 4.9,
    reviewCount: 203,
    verificationStatus: 'VERIFIED',
    distanceKm: 14.1,
    responseTime: '< 3 hours',
    priceRange: '₹₹₹',
    capabilities: ['5-Axis CNC', 'CMM Inspection', 'Design Support', 'CNC Machining'],
    certifications: ['ISO 9001', 'AS9100', 'IATF 16949'],
    specialties: ['Defense', 'Precision Aerospace'],
    machines: [],
  },
];

export const INITIAL_BIDS: IQuotation[] = [
  {
    id: 'bid-1',
    quoteCode: 'QUO-001',
    enquiryId: 'enq-001',
    manufacturerId: 'mfg-001',
    manufacturer: {
      pseudoName: 'Metro Manufacturing Co.',
      city: 'Pune, MH',
      rating: 4.6,
      reviewCount: 98,
      capabilities: ['CNC Machining', 'Laser Cutting', 'Assembly'],
      certifications: ['ISO 9001', 'ISO 14001'],
    },
    totalCostInr: 2850,
    leadTimeDays: 7,
    deliveryDate: '5-8 days',
    notes: 'High-volume manufacturer with quick turnaround times and competitive pricing.',
    status: 'PENDING',
  },
  {
    id: 'bid-2',
    quoteCode: 'QUO-002',
    enquiryId: 'enq-001',
    manufacturerId: 'mfg-002',
    manufacturer: {
      pseudoName: 'Precision Tech Industries',
      city: 'Indore, MP',
      rating: 4.8,
      reviewCount: 142,
      capabilities: ['CNC Machining', 'Anodizing', 'Quality Inspection'],
      certifications: ['ISO 9001', 'AS9100'],
    },
    totalCostInr: 3200,
    leadTimeDays: 9,
    deliveryDate: '7-10 days',
    notes: 'Specialized in precision CNC machining with aerospace-grade quality standards.',
    status: 'PENDING',
  },
  {
    id: 'bid-3',
    quoteCode: 'QUO-003',
    enquiryId: 'enq-001',
    manufacturerId: 'mfg-003',
    manufacturer: {
      pseudoName: 'Gujarat Engineering Works',
      city: 'Ahmedabad, GJ',
      rating: 4.5,
      reviewCount: 76,
      capabilities: ['CNC Machining', 'Heat Treatment', 'Surface Coating'],
      certifications: ['ISO 9001'],
    },
    totalCostInr: 3850,
    leadTimeDays: 12,
    deliveryDate: '10-14 days',
    notes: 'Family-owned business with 25+ years of experience in precision manufacturing.',
    status: 'PENDING',
  },
  {
    id: 'bid-4',
    quoteCode: 'QUO-004',
    enquiryId: 'enq-001',
    manufacturerId: 'mfg-004',
    manufacturer: {
      pseudoName: 'Advanced Machining Solutions',
      city: 'Pune, MH',
      rating: 4.9,
      reviewCount: 203,
      capabilities: ['5-Axis CNC', 'CMM Inspection', 'Design Support'],
      certifications: ['ISO 9001', 'AS9100', 'IATF 16949'],
    },
    totalCostInr: 4200,
    leadTimeDays: 8,
    deliveryDate: '6-9 days',
    notes: 'Premium manufacturer offering advanced 5-axis capabilities and engineering support.',
    status: 'PENDING',
  },
];

export const INITIAL_JOBS = [
  {
    id: 'job-1',
    code: 'FAB-2024-1892',
    title: 'Custom Aluminum Brackets - 500 units',
    client: 'TechCorp Solutions',
    status: 'In Production',
    priority: 'High',
    budget: '$12,000 - $18,000',
    quotesCount: 7,
    manager: 'Sarah Johnson',
    date: '2024-07-08',
  },
  {
    id: 'job-2',
    code: 'FAB-2024-1891',
    title: 'Prototype CNC Machining',
    client: 'StartupXYZ',
    status: 'Quoted',
    priority: 'Medium',
    budget: '$2,000 - $3,500',
    quotesCount: 3,
    manager: 'Unassigned',
    date: '2024-07-10',
  },
  {
    id: 'job-3',
    code: 'FAB-2024-1890',
    title: 'Sheet Metal Fabrication - Complex Assembly',
    client: 'Industrial Systems Inc',
    status: 'Open',
    priority: 'High',
    budget: '$25,000 - $35,000',
    quotesCount: 2,
    manager: 'Unassigned',
    date: '2024-07-11',
  },
  {
    id: 'job-4',
    code: 'FAB-2024-1889',
    title: '3D Printed Components - 100 pieces',
    client: 'Design Studio Pro',
    status: 'Completed',
    priority: 'Low',
    budget: '$800 - $1,200',
    quotesCount: 12,
    manager: 'Mike Chen',
    date: '2024-06-15',
  },
];

export const INITIAL_DISPUTES: IDispute[] = [
  {
    id: 'dis-1',
    disputeCode: 'DIS-001',
    orderNumber: 'FAB-2024-1892',
    jobTitle: 'Custom Aluminum Brackets',
    clientName: 'TechCorp Solutions',
    manufacturerPseudo: 'Precision Manufacturing LLC',
    issueType: 'Quality Issue',
    priority: 'High',
    status: 'Open',
    valueInr: 15750,
    reportedDate: '2024-07-10',
  },
  {
    id: 'dis-2',
    disputeCode: 'DIS-002',
    orderNumber: 'FAB-2024-1888',
    jobTitle: 'Prototype Components',
    clientName: 'StartupXYZ',
    manufacturerPseudo: 'Metro Metalworks',
    issueType: 'Delivery Delay',
    priority: 'Medium',
    status: 'In Progress',
    valueInr: 8200,
    reportedDate: '2024-07-08',
  },
  {
    id: 'dis-3',
    disputeCode: 'DIS-003',
    orderNumber: 'FAB-2024-1885',
    jobTitle: 'Sheet Metal Assembly',
    clientName: 'Industrial Systems Inc',
    manufacturerPseudo: 'Advanced Fabrication Co',
    issueType: 'Communication',
    priority: 'Low',
    status: 'Resolved',
    valueInr: 22100,
    reportedDate: '2024-07-05',
  },
];
